//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Game/Scripts/Input/GameInputAsset.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputAsset : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputAsset()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputAsset"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""17c19986-2aa5-457f-8648-3300bfc7f17f"",
            ""actions"": [
                {
                    ""name"": ""Walk"",
                    ""type"": ""Value"",
                    ""id"": ""e114547b-28dd-4997-a094-05833689c554"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""30f14109-b240-41ed-a74d-e8f294d1581d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldBreak"",
                    ""type"": ""Button"",
                    ""id"": ""0dc4f30a-dcb7-46ad-ab94-9dc13dbf12cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MultiTapBreak"",
                    ""type"": ""Button"",
                    ""id"": ""dbfdac6a-d9f0-49ad-b23b-ff18a7abb208"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""872bc5bf-d1b0-4c5d-8553-51ff7f40013f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""56dbb424-6db9-404a-9f5f-abbecfcd3729"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d7bf6d07-7fd2-4934-a10b-82e4cbd24285"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f6ea1f0e-fd66-4d45-8167-5418442eeab7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2f5bfe46-57ed-413e-8b6c-341c83410da5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3939cb0f-23c9-4298-9eda-9a0b9b0c0731"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""801e2da9-a1c4-44e1-8fda-be797d57ffc2"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldBreak"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c50aa45-244a-449c-a812-3534f48044ec"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""MultiTap(tapCount=3)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MultiTapBreak"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Hacked"",
            ""id"": ""177bd62a-0d34-49df-8558-1e4d35bc12a1"",
            ""actions"": [
                {
                    ""name"": ""ChangeCameras"",
                    ""type"": ""Button"",
                    ""id"": ""baf3b1e2-ce1f-468c-87c9-b89a16e89662"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""8188c5b1-e5c4-47c6-b8fa-40adfc9fac7f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0c23976f-35f2-4864-9966-7dbbb03935cc"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeCameras"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66b21087-0f11-447e-93c9-71ac19edcac9"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Forklift"",
            ""id"": ""a1d50013-5578-4b58-bb98-a7ce81b16e0c"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""256ae82f-1580-4805-9dd6-48b2c9c01e69"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1d8819e2-e9bf-4a09-95ae-4b9f7e822133"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Drone"",
            ""id"": ""4b67c820-efb3-4d85-98af-aa615d9e6c87"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""bddd01a7-331f-4f51-88a2-6569a897c536"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2f6e461f-c12b-4ed5-903c-44842cab01a3"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Walk = m_Player.FindAction("Walk", throwIfNotFound: true);
        m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
        m_Player_HoldBreak = m_Player.FindAction("HoldBreak", throwIfNotFound: true);
        m_Player_MultiTapBreak = m_Player.FindAction("MultiTapBreak", throwIfNotFound: true);
        // Hacked
        m_Hacked = asset.FindActionMap("Hacked", throwIfNotFound: true);
        m_Hacked_ChangeCameras = m_Hacked.FindAction("ChangeCameras", throwIfNotFound: true);
        m_Hacked_Exit = m_Hacked.FindAction("Exit", throwIfNotFound: true);
        // Forklift
        m_Forklift = asset.FindActionMap("Forklift", throwIfNotFound: true);
        m_Forklift_Newaction = m_Forklift.FindAction("New action", throwIfNotFound: true);
        // Drone
        m_Drone = asset.FindActionMap("Drone", throwIfNotFound: true);
        m_Drone_Newaction = m_Drone.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Walk;
    private readonly InputAction m_Player_Interact;
    private readonly InputAction m_Player_HoldBreak;
    private readonly InputAction m_Player_MultiTapBreak;
    public struct PlayerActions
    {
        private @GameInputAsset m_Wrapper;
        public PlayerActions(@GameInputAsset wrapper) { m_Wrapper = wrapper; }
        public InputAction @Walk => m_Wrapper.m_Player_Walk;
        public InputAction @Interact => m_Wrapper.m_Player_Interact;
        public InputAction @HoldBreak => m_Wrapper.m_Player_HoldBreak;
        public InputAction @MultiTapBreak => m_Wrapper.m_Player_MultiTapBreak;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Walk.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWalk;
                @Walk.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWalk;
                @Walk.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWalk;
                @Interact.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteract;
                @HoldBreak.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldBreak;
                @HoldBreak.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldBreak;
                @HoldBreak.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldBreak;
                @MultiTapBreak.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMultiTapBreak;
                @MultiTapBreak.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMultiTapBreak;
                @MultiTapBreak.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMultiTapBreak;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Walk.started += instance.OnWalk;
                @Walk.performed += instance.OnWalk;
                @Walk.canceled += instance.OnWalk;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @HoldBreak.started += instance.OnHoldBreak;
                @HoldBreak.performed += instance.OnHoldBreak;
                @HoldBreak.canceled += instance.OnHoldBreak;
                @MultiTapBreak.started += instance.OnMultiTapBreak;
                @MultiTapBreak.performed += instance.OnMultiTapBreak;
                @MultiTapBreak.canceled += instance.OnMultiTapBreak;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Hacked
    private readonly InputActionMap m_Hacked;
    private IHackedActions m_HackedActionsCallbackInterface;
    private readonly InputAction m_Hacked_ChangeCameras;
    private readonly InputAction m_Hacked_Exit;
    public struct HackedActions
    {
        private @GameInputAsset m_Wrapper;
        public HackedActions(@GameInputAsset wrapper) { m_Wrapper = wrapper; }
        public InputAction @ChangeCameras => m_Wrapper.m_Hacked_ChangeCameras;
        public InputAction @Exit => m_Wrapper.m_Hacked_Exit;
        public InputActionMap Get() { return m_Wrapper.m_Hacked; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HackedActions set) { return set.Get(); }
        public void SetCallbacks(IHackedActions instance)
        {
            if (m_Wrapper.m_HackedActionsCallbackInterface != null)
            {
                @ChangeCameras.started -= m_Wrapper.m_HackedActionsCallbackInterface.OnChangeCameras;
                @ChangeCameras.performed -= m_Wrapper.m_HackedActionsCallbackInterface.OnChangeCameras;
                @ChangeCameras.canceled -= m_Wrapper.m_HackedActionsCallbackInterface.OnChangeCameras;
                @Exit.started -= m_Wrapper.m_HackedActionsCallbackInterface.OnExit;
                @Exit.performed -= m_Wrapper.m_HackedActionsCallbackInterface.OnExit;
                @Exit.canceled -= m_Wrapper.m_HackedActionsCallbackInterface.OnExit;
            }
            m_Wrapper.m_HackedActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ChangeCameras.started += instance.OnChangeCameras;
                @ChangeCameras.performed += instance.OnChangeCameras;
                @ChangeCameras.canceled += instance.OnChangeCameras;
                @Exit.started += instance.OnExit;
                @Exit.performed += instance.OnExit;
                @Exit.canceled += instance.OnExit;
            }
        }
    }
    public HackedActions @Hacked => new HackedActions(this);

    // Forklift
    private readonly InputActionMap m_Forklift;
    private IForkliftActions m_ForkliftActionsCallbackInterface;
    private readonly InputAction m_Forklift_Newaction;
    public struct ForkliftActions
    {
        private @GameInputAsset m_Wrapper;
        public ForkliftActions(@GameInputAsset wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Forklift_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Forklift; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ForkliftActions set) { return set.Get(); }
        public void SetCallbacks(IForkliftActions instance)
        {
            if (m_Wrapper.m_ForkliftActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_ForkliftActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_ForkliftActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_ForkliftActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_ForkliftActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public ForkliftActions @Forklift => new ForkliftActions(this);

    // Drone
    private readonly InputActionMap m_Drone;
    private IDroneActions m_DroneActionsCallbackInterface;
    private readonly InputAction m_Drone_Newaction;
    public struct DroneActions
    {
        private @GameInputAsset m_Wrapper;
        public DroneActions(@GameInputAsset wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Drone_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Drone; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DroneActions set) { return set.Get(); }
        public void SetCallbacks(IDroneActions instance)
        {
            if (m_Wrapper.m_DroneActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_DroneActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_DroneActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_DroneActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_DroneActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public DroneActions @Drone => new DroneActions(this);
    public interface IPlayerActions
    {
        void OnWalk(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnHoldBreak(InputAction.CallbackContext context);
        void OnMultiTapBreak(InputAction.CallbackContext context);
    }
    public interface IHackedActions
    {
        void OnChangeCameras(InputAction.CallbackContext context);
        void OnExit(InputAction.CallbackContext context);
    }
    public interface IForkliftActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IDroneActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
